// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6e6CKGx1QeysVQwZ4yGk-ZhkIzQ6XHc',
    appId: '1:174024575705:web:2eb3def0dff1a82d1eccc8',
    messagingSenderId: '174024575705',
    projectId: 'facial-recognition-abc',
    authDomain: 'facial-recognition-abc.firebaseapp.com',
    storageBucket: 'facial-recognition-abc.appspot.com',
    measurementId: 'G-C37T7Q5WSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3mLtFsCDGQ0gNgPF47n_6g3wRDZdqg64',
    appId: '1:174024575705:android:a4b90323d0a67e7f1eccc8',
    messagingSenderId: '174024575705',
    projectId: 'facial-recognition-abc',
    storageBucket: 'facial-recognition-abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpDTohLFOtF1Fqg5ES8GoTlitX3MMm82Q',
    appId: '1:174024575705:ios:4ec5736b33baf9161eccc8',
    messagingSenderId: '174024575705',
    projectId: 'facial-recognition-abc',
    storageBucket: 'facial-recognition-abc.appspot.com',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpDTohLFOtF1Fqg5ES8GoTlitX3MMm82Q',
    appId: '1:174024575705:ios:4ec5736b33baf9161eccc8',
    messagingSenderId: '174024575705',
    projectId: 'facial-recognition-abc',
    storageBucket: 'facial-recognition-abc.appspot.com',
    iosBundleId: 'com.example.faceAuth',
  );
}
